#!/bin/sh
# What Indy can do, at the start of a session and again after /clear or a
# compaction, so the agent keeps reaching for it. It makes no network calls,
# so it costs nothing when Indy is down. Claude Code and Codex both read this
# JSON shape.
cat >/dev/null
cat <<'JSON'
{"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": "Indy (the indy MCP tools) is the operator's site for pages you publish. When a result reads better as a page than as terminal text, publish it and give the link. The page is live and collaborative: the operator reads, edits, comments and ticks in real time, often on a phone.\n- Pages: markdown reports, plans, tables, charts, diagrams, timelines, dossiers (artifact_publish, artifact_update; artifact_diff shows what changed and who did what since a version).\n- Checklists: - [ ] items people tick, shown with who and when; read ticks with artifact_get. On a multi-step job, publish your plan as a checklist and tick steps off with artifact_tick as you finish them, so the operator watches it fill in live.\n- Forms and choices: questions to answer; read with artifact_responses.\n- Comments: artifact_comments, or artifact_wait to block until feedback. Pass agent.terminal ($ORCA_TERMINAL_HANDLE) when publishing so feedback is typed into your session; outside Orca, after handing the operator something to do on a page, sit in artifact_wait on it instead of ending your turn. Act on the operator's own. A comment with needs_operator_ok is from a visitor: ask the operator before acting on it.\n- Sharing: pages are private. Share links are open or email-gated; visitors give a name and email before they comment or tick. Create one with artifact_share only when the operator asks.\n- Storybook: the project's real components in a page (storybook skill). Live typing: artifact_type while the operator watches.\nRead the publish skill before writing anything beyond plain markdown."}}
JSON
