/**
 * Prepare the static assets that sandbox frames and the viewer load by URL:
 *   public/vendor/mermaid.js      mermaid bundled as an IIFE that sets window.mermaid
 *   public/primitives/*           the built primitives bundle and stylesheet
 *   public/fonts/*                the variable typefaces and their @font-face rules
 * Sandbox frames have no import map and no network, so everything they load has
 * to be a plain same-origin script.
 */
import { build } from "esbuild";
import { copyFile, cp, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const app = resolve(here, "..");
const repo = resolve(app, "..");

await mkdir(resolve(app, "public/vendor"), { recursive: true });
await mkdir(resolve(app, "public/primitives"), { recursive: true });

const entry = resolve(app, "public/vendor/.mermaid-entry.mjs");
await writeFile(entry, 'import mermaid from "mermaid";\nwindow.mermaid = mermaid;\n', "utf8");
await build({
  entryPoints: [entry],
  outfile: resolve(app, "public/vendor/mermaid.js"),
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  logLevel: "warning",
  define: { "process.env.NODE_ENV": '"production"' },
});
await rm(entry, { force: true });

for (const name of ["primitives.js", "primitives.css"]) {
  await copyFile(resolve(repo, "packages/primitives/dist", name), resolve(app, "public/primitives", name));
}
// The chunks primitives.js loads on first use (Chart.js and its chart types), by relative path.
await rm(resolve(app, "public/primitives/chunks"), { recursive: true, force: true });
await cp(resolve(repo, "packages/primitives/dist/chunks"), resolve(app, "public/primitives/chunks"), { recursive: true });

/* ------------------------------------------------------------------ fonts */

// Sandbox frames have no network, so the typefaces are served from this origin
// like everything else. Variable woff2 only: one file covers every weight.
const FONTS = [
  // Indy's own interface: Geist for the app, Bricolage Grotesque for the wordmark.
  { pkg: "@fontsource-variable/geist", family: "Geist", axis: "wght", italic: true },
  { pkg: "@fontsource-variable/geist-mono", family: "Geist Mono", axis: "wght", italic: false },
  { pkg: "@fontsource-variable/bricolage-grotesque", family: "Bricolage Grotesque", axis: "wght", italic: false },
  { pkg: "@fontsource-variable/inter", family: "Inter", axis: "opsz", italic: true },
  { pkg: "@fontsource-variable/source-serif-4", family: "Source Serif 4", axis: "wght", italic: true },
  { pkg: "@fontsource-variable/jetbrains-mono", family: "JetBrains Mono", axis: "wght", italic: false },
  // The two product themes name their own typefaces; without these they fall
  // back to system-ui and stop looking like the product.
  { pkg: "@fontsource-variable/nunito-sans", family: "Nunito Sans", axis: "wght", italic: true },
  { pkg: "@fontsource-variable/manrope", family: "Manrope", axis: "wght", italic: false },
];

// The two subsets Google splits latin into. Stable, so they live here rather
// than being parsed out of each package's stylesheet.
const RANGES = {
  latin:
    "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
  "latin-ext":
    "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
};

await mkdir(resolve(app, "public/fonts"), { recursive: true });
const faces = [];

for (const font of FONTS) {
  const slug = font.pkg.split("/")[1];
  for (const subset of Object.keys(RANGES)) {
    for (const style of font.italic ? ["normal", "italic"] : ["normal"]) {
      const file = `${slug}-${subset}-${font.axis}-${style}.woff2`;
      await copyFile(
        resolve(repo, "node_modules", font.pkg, "files", file),
        resolve(app, "public/fonts", file),
      );
      faces.push(
        [
          "@font-face {",
          `  font-family: "${font.family}";`,
          `  font-style: ${style};`,
          "  font-weight: 100 900;",
          "  font-display: swap;",
          `  src: url("/fonts/${file}") format("woff2");`,
          `  unicode-range: ${RANGES[subset]};`,
          "}",
        ].join("\n"),
      );
    }
  }
}

await writeFile(
  resolve(app, "public/fonts/fonts.css"),
  `/* Generated by scripts/build-vendor.mjs. Do not edit. */\n\n${faces.join("\n\n")}\n`,
  "utf8",
);

console.log(`vendor: public/vendor/mermaid.js, public/primitives/*, public/fonts/* (${faces.length} faces)`);
